# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.4
_src_path: https://github.com/jupyterlab/extension-template
author_email: ernestrsage@gmail.com
author_name: ernest
data_format: string
file_extension: ''
has_binder: true
has_settings: true
kind: frontend
labextension_name: ycextension
mimetype: ''
mimetype_name: ''
project_short_description: A JupyterLab extension for Yandex Cloud.
python_name: ycextension
repository: https://github.com/sesh00/ycextension
test: true
viewer_name: ''

